### ISSUE TITLE
Support El Capitan (macOS 10.11)

### ISSUE THREAD

**Issue by zlshames** [codebytere/node-mac-contacts#44]
Currently the library only seems to support 10.13+ due to the Permissions.node file being compiled on 10.13. Is there a way we can get support for 10.11? or even 10.12? 

Error:

```
Uncaught Exception:
Error: dlopen(/Applications/x.app/Contents/Resources/app.asar.unpacked/node_modules/node-mac-permissions/build/Release/permissions.node, 1): Symbol not found: OBJC_CLASS$_PHPhotoLibrary
Referenced from: /Applications/x.app/Contents/Resources/app.asar.unpacked/node_modules/node-mac-permissions/build/Release/permissions.node (which was built for Mac OS X 10.13)
Expected in: /System/Library/Frameworks/Photos.framework/Versions/A/Photos
in /Applications/x.app/Contents/Resources/app.asar.unpacked/node_modules/node-mac-permissions/build/Release/permissions.node
at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
at Module.load (node:internal/modules/cjs/loader:988:32)
at Module._load (node:internal/modules/cjs/loader:829:12)
at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
at Module.require (node:internal/modules/cjs/loader:1012:19)
at require (node:internal/modules/cjs/helpers:102:18)
at bindings (/Applications/x.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:112:48)
at Object. (/Applications/x.app/Contents/Resources/app.asar/node_modules/node-mac-permissions/index.js:1:40)
```

**Comment by codebytere** [comment]
@zlshames i'm sorry but no - there's a balance to be struck between supporting some older systems and phasing them out and I do genuinely hear that but most/many major apps and platforms have moved past 10.13. Chromium sets its minimum to 10.15 at this point, and Node.js' minimum for v20.x is 11.0 - I'm still supporting farther back than that but will also likely consider bumping my minimum required version soon.

**Comment by zlshames** [comment]
> @zlshames i'm sorry but no - there's a balance to be struck between supporting some older systems and phasing them out and I do genuinely hear that but most/many major apps and platforms have moved past 10.13. Chromium sets its minimum to 10.15 at this point, and Node.js' minimum for v20.x is 11.0 - I'm still supporting farther back than that but will also likely consider bumping my minimum required version soon.

No worries, i get that. It was a shot in the dark. But i agree with you. We'll just drop El Capitan support :)
